name: Deploy Terraform
on: 
#  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

jobs:
  test-merge:

    environment:
      name: atest


    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context.repo)

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(github.issue)

      - name: Guess PR
        run: |
          export PR=$( echo '${{ toJSON(github.event.head_commit.message) }}' | sed 's/.*#\([0-9]*\).*/\1/g' )
          #export PR=$( echo '${{toJSON(github.event.head_commit)}}' | jq '.message' | sed 's/.*#\([0-9]*\).*/\1/g' )
          echo "PRNUM=${PR}" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ env.PRNUM }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 PUSH detected from PR ${{ env.PRNUM }}!'
            })
        if: ${{ env.PRNUM != 'null' }}
