name: Deploy Terraform
on: 
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

jobs:
  test-merge:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context.repo)

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(github.issue)

      - name: Stuff 
        run: |
          echo "${{toJSON(github.event)}}"
          #echo "${{ github.event.head_commit.message }}"
          #echo ${{ github.event.head_commit.message }}
          #echo -n "${{ github.event.head_commit.message }}"

      - name: Guess PR
        run: |
          echo "PRNUM=$(echo '${{ github.event.head_commit.message }}' | sed 's/.*#\([0-9]*\).*/\1/g')" >> $GITHUB_ENV

    
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ env.PRNUM }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
        if: ${{ env.PRNUM != '' }}
