name: Deploy Terraform
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test-merge:
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context.repo)

      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: console.log(github.issue)
